---
title: "Lab 5"
author: "Christine Gormley"
date: "`r Sys.Date()` "
output:
  html_document:
    toc: yes 
    toc_float: yes 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Task 1 

```{r}
getwd()
```

# Task 2

```{r}
mybin=function(iter=100,n=10, p=0.5){ 
  
sam.mat=matrix(NA,nr=n,nc=iter, byrow=TRUE)

succ=c()
for( i in 1:iter){

sam.mat[,i]=sample(c(1,0),n,replace=TRUE, prob=c(p,1-p))

succ[i]=sum(sam.mat[,i])
}

succ.tab=table(factor(succ,levels=0:n))

barplot(succ.tab/(iter), col=rainbow(n+1), main="Binomial simulation", xlab="Number of successes")
succ.tab/iter
}


```

# iter=100, n=10, p=0.7
```{r}
bin1 = mybin(iter=100,n=10, p=0.7)
```


# iter= 200, n=10, p=0.7
```{r}

bin200= mybin(iter=200,n=10, p=0.7)

```

# iter= 500, n=10, p=0.7
```{r}

bin500= mybin(iter=500,n=10, p=0.7)
```

# iter= 1000, n=10, p=0.7 

```{r}

bin1000= mybin(iter=1000,n=10, p=0.7)
```

# iter= 10000, n=10, p=0.7 
```{r}

bin10000= mybin(iter=10000,n=10, p=0.7)

```


# Table From iter = 10000 

```{r}
bin10000
```

     
     0      1      2      3      4      5      6      7      8      9     10 
0.0000 0.0002 0.0010 0.0086 0.0354 0.0974 0.1944 0.2696 0.2420 0.1244 0.0270 


# Verify Each Value is Approximately Correct 
```{r}
dbinom10000=round(dbinom(0:10, size= 10, prob= 0.7), 4)
names(dbinom10000) = 0:10
dbinom10000
```



# Task 3 

```{r}
sample(c(1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0),size=5,prob= NULL, replace= FALSE)
```
```{r}
sample(c(1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0), size = 5, prob= NULL, replace= TRUE)
```

# Hyper function 
```{r}
myhyper=function(iter=100,N=20,r=12,n=5){

sam.mat=matrix(NA,nr=n,nc=iter, byrow=TRUE)
succ=c()
for( i in 1:iter){

sam.mat[,i]=sample(rep(c(1,0),c(r,N-r)),n,replace=FALSE)

succ[i]=sum(sam.mat[,i])
}
# Make table of successes
succ.tab=table(factor(succ,levels=0:n))

barplot(succ.tab/(iter), col=rainbow(n+1), main="HYPERGEOMETRIC simulation", xlab="Number of successes")
succ.tab/iter
}


```


```{r}
myhyper1= myhyper(iter=100, N=20,r=12, n = 5)
```

```{r}
myhyper2= myhyper(iter=200, N=20,r=12, n = 5)
```

```{r}
myhyper3= myhyper(iter=500,N=20,r=12, n=5)
```

```{r}
myhyper4= myhyper(iter=1000, N=20,r=12, n=5)
```

```{r}
myhyper5= myhyper(iter=10000, N=20,r=12, n=5)
```


```{r}
dhyper10000= round(dhyper(x= 0:10, m= 12, k=6 , n= 5 ), 4) 
names(dhyper10000)= 0:10 
dhyper10000
```

# Task 4 



```{r}
mysample=function(n, iter=10,time=0.5){
for( i in 1:iter){
# Make a sample
s=sample(1:10,n,replace=TRUE)

sf=factor(s,levels=1:10)
# Make a barplot
barplot(table(sf)/n,beside=TRUE,col=rainbow(10), 
main=paste("Example sample()", " iteration ", i, " n= ", n,sep="") ,
ylim=c(0,0.2)
)
Sys.sleep(time)
}
}

mysample(n=1000,time=1, iter=1)
```
When I ran the plot with 30 iterations I saw 30 different plots when we take 10 samples in the time of 1 second. 





# Task 5 

```{r}
choose(8,4)
```

```{r}
1-ppois(q=3 , lambda=2)
```
# P(Y=10),Y~NegBin(p=0.4,r=3) 
```{r}
choose(8,4)*0.4^3*0.4^(10-3)
```
# 	P(Y≤8),Y~Bin(n=15,p=0.4)
```{r}
1 - pnbinom(q=8-0.4,size=15,prob=0.4)
```

# Task 6

```{r}
library(MATH4753CG)
scatterhist
```


```{r}
?dbinom
```

