---
title: "Lab 6"
author: "Christine Gormley"
date: "`r Sys.Date()` "
output:
 html_document:
    toc: yes 
    toc_float: yes
      
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




# Task 1 

```{r}
getwd()
```
# Task 2 

```{r}
# This code creates 4 curved graphs showing the densities
layout(matrix(1:4, nr=2,nc=2))

layout.show(4)

# This code creates a curve of the density distrbtuion function for the mean and standard deviation 

curve(dnorm(x, mean=10,sd=4),xlim=c(10 - 3*4, 10+(3*4)))

curve(dnorm(x, mean=10,sd=2),xlim=c(10-(3*2), 10+(3*2)))

curve(dnorm(x, mean=5,sd=10),xlim=c(5-(3*10),5+ (3*10)))

curve(dnorm(x, mean=5,sd=0.5),xlim=c(5-(3*0.5), 5 + (3*0.5)))

pnorm(-2,-2,0.5) - pnorm(-3,-2,0.5)



```



```{r}
# Created a function to get four graphs. 
layout(matrix(1:4, nr= 2 , nc=2))
layout.show(4)

# This curve function plots the curve for the density distribution function of a normal distribution. 

curve(dnorm(x, mean=0,sd=1), xlim=c(0,4))

xcurve=seq(0,4,length=1000)

ycurve=dnorm(xcurve,mean=0,sd=1)

polygon(c(0,xcurve,4),c(0,ycurve,0),col="Yellow")


area = pnorm(4, mean= 0, sd=1 )-pnorm(0, mean= 0, sd= 1)
area=round(area,4)

text(x= 1, y= 0.20 , paste("Area = ", area, sep=""))




curve(dnorm(x, mean=4,sd=2), xlim=c(-2,12))

xcurve=seq(1,5,length=1000)

ycurve=dnorm(xcurve,mean=4,sd=2)

polygon(c(1,xcurve,5),c(0,ycurve,0),col="Yellow")


area = pnorm(5, mean= 4, sd=2 )-pnorm(1, mean= 4, sd= 2)
area=round(area,4)

text(x= 1, y= 0.05 , paste("Area = ", area , sep=""))


curve(dnorm(x, mean=10,sd=4), xlim=c(-2,12))

xcurve=seq(1,5,length=1000)

ycurve=dnorm(xcurve,mean=10,sd=4)

polygon(c(1,xcurve,5),c(0,ycurve,0),col="Yellow")


area = pnorm(5, mean= 10, sd=4 )-pnorm(1, mean= 10, sd= 4)
area=round(area,4)

text(x= 2, y= 0.05 , paste("Area = ", area, sep=""))




curve(dnorm(x, mean=-2,sd=0.5), xlim=c(-5,2))

xcurve=seq(-5,2,length=1000)

ycurve=dnorm(xcurve,mean=-2,sd=0.5)
polygon(c(-5,xcurve,2),c(0,ycurve,0),col="Yellow")


area = pnorm(2, mean= -2, sd=0.5 )-pnorm(-5, mean= -2, sd = 0.5)
area=round(area,4)

text(x= -2, y= 0.20 , paste("Area = ", area, sep=""))












```





# Task 3 

# Gamma Distributions 

```{r}
curve(dgamma(x,shape=1,scale=1),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2,
ylab="Gamma density", main="Beta=1")

curve(dgamma(x,shape=3,scale=1),xlim=c(0,10),ylim=c(0,1),add=TRUE,lwd=2)

curve(dgamma(x,shape=5,scale=1),xlim=c(0,10),ylim=c(0,1),add=TRUE, col="Blue",lwd=2)


```
# Probability 
```{r}
layout(matrix(1:3, nr=1,nc=3))

layout.show(3)

curve(dgamma(x,shape=3,scale=2),xlim=c(0,10),ylim=c(0,0.4),col="Red",lwd=2,

ylab="Gamma density", xlab= "X", main="Shape 3 Scale 2")

xcurve= seq(2,5, length= 1000)

ycurve= dgamma(xcurve, shape=3, scale=2)

polygon(c(2, xcurve, 5), c(0, ycurve, 0), col= "Yellow")

# For Area 

area = pgamma(5, shape= 3, scale=2)-pgamma(2, shape = 3, scale = 2)
area=round(area,4)

text(x= 4, y= 0.01 , paste("Area = ", area, sep=""))





curve(dgamma(x,shape=6,scale=3),xlim=c(0,6),ylim=c(0,0.020),col="Purple",lwd=2,

ylab="Gamma density", xlab= "X", main="Shape 6 Scale 3") 

xcurve= seq(1,4, length= 1000)

ycurve= dgamma(xcurve, shape=6, scale=3)

polygon(c(1, xcurve, 4), c(0, ycurve, 0), col= "Yellow")

# For Area 

area = pgamma(4, shape= 6, scale=3)-pgamma(1, shape = 6, scale = 3)
area=round(area,4)

text(x= 4, y= 0.001 , paste("Area = ", area, sep=""))






curve(dgamma(x,shape=2,scale=4),xlim=c(0,10),ylim=c(0,0.3),col="Green",lwd=2,

ylab="Gamma density", xlab= "X", main="Shape 2 Scale 4")

xcurve= seq(3,6, length= 1000)

ycurve= dgamma(xcurve, shape=2, scale=4)

polygon(c(3, xcurve, 6), c(0, ycurve, 0), col= "Yellow")

# For Area 

area = pgamma(6, shape= 2, scale=4)-pgamma(3, shape = 2, scale = 4)
area=round(area,4)

text(x= 5, y= 0.002 , paste("Area = ", area, sep=""))

```





# Task 4 

# Chi-Square Distribution

```{r}
layout(matrix(1:4, nr= 2, nc=2))
layout.show(4)

# These plots plot the chi-square distribution. 

curve(dchisq(x,df=1),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2,
ylab="Chisq density", main="df= 1") 

curve(dchisq(x,df=2),xlim=c(0,10),ylim=c(0,1),col="Blue",lwd=2,
ylab="Chisq density",main= "df= 2") 

curve(dchisq(x,df=4),xlim=c(0,10),ylim=c(0,1),col="Red",lwd=2,
ylab="Chisq density", main="df= 4")

curve(dchisq(x,df=20),xlim=c(0,10),ylim=c(0,0.03),col="Blue",lwd=2,
ylab="Chisq density", main= "df= 20 ")
```

```{r}
layout(matrix(1:3, nr= 1 , nc=3))
layout.show(3)

curve(dchisq(x,df=2),xlim=c(0,10),ylim=c(0,0.20),col="Red",lwd=2,
ylab="Chisq density", xlab= "X", main="Degrees of Freedon = 2")

xcurve= seq(2,4,length=1000) 

ycurve= dchisq(xcurve, df=2)

polygon(c(2,xcurve,4), c(0,ycurve,0), col= "Yellow")

area = pchisq(4, df=2)- pchisq(2, df=2)
area=round(area,4)

text(x=2, y= 0.025, paste("Area= ", area, sep= ""))


curve(dchisq(x,df=3),xlim=c(0,10),ylim=c(0,0.27),col="Red",lwd=2,
ylab="Chisq density", xlab= "X", main="Degrees of Freedon = 3")

xcurve= seq(3,5, length= 1000)

ycurve= dchisq(xcurve, df=3)

polygon(c(3, xcurve, 5), c(0,ycurve,0), col= "Yellow")

area= pchisq(5, df=3)- pchisq(3, df=3)
area=round(area,4)

text(x=3, y=0.025, paste("Area= ", area, sep= ""))



curve(dchisq(x,df=20),xlim=c(0,30),ylim=c(0,0.1),col="Red",lwd=2,
ylab="Chisq density", xlab= "X", main="Degrees of Freedon = 20")

xcurve= seq(10,21, length= 1000)
  
ycurve= dchisq(xcurve, df=20)

polygon(c(10, xcurve, 21), c(0,ycurve,0), col= "Yellow")

area=pchisq(21,df=20)-pchisq(10,df=20)
area=round(area,4)

text(x=20, y=0.03, paste("Area= ", area, sep= ""))
  









```

# Task 5 

# Weibull 

```{r}
layout(matrix(1:4, nr= 2 , nc= 2))
layout.show(4)



curve(dweibull(x,shape=4,scale=6),xlim=c(0,9),ylim=c(0,1),col="Red",lwd=2,

ylab="Weibull density", xlab= "X", main="Shape 4 Scale 6")

xcurve= seq(2,8, length= 1000)

ycurve= dweibull(xcurve, shape=4, scale=6)

polygon(c(2, xcurve, 8), c(0, ycurve, 0), col= "Yellow")

# For the area calculation

area = pweibull(8, shape= 4, scale=6)-pweibull(2, shape = 4, scale = 6)
area=round(area,4)

text(x= 5, y= 0.1, paste("Area= ", area, sep= ""))


# Y ~ dweibull(shape= 5 ,scale= 2) P(1≤Y≤3)

curve(dweibull(x,shape=5,scale=2),xlim=c(0,4),ylim=c(0,1),col="Red",lwd=2,

ylab="Weibull density", xlab= "X", main="Shape 5 Scale 2")

xcurve= seq(1,3, length= 1000)

ycurve= dweibull(xcurve, shape=5, scale=2)

polygon(c(1, xcurve, 3), c(0, ycurve, 0), col= "Yellow")

# For the area calculation

area = pweibull(3, shape= 5, scale=2)-pweibull(1, shape = 5, scale = 2)
area=round(area,4)

text(x= 2, y= 0.2, paste("Area= ", area, sep= ""))

# Y~ dweibull (shape= 1, scale=9), P(2≤Y<6)


curve(dweibull(x,shape=1,scale=9),xlim=c(0,8),ylim=c(0,0.4),col="Red",lwd=2,

ylab="Weibull density", xlab= "X", main="Shape 1 Scale 9")

xcurve= seq(2,6, length= 1000)

ycurve= dweibull(xcurve, shape=1, scale=9)

polygon(c(2, xcurve, 6), c(0, ycurve, 0), col= "Yellow")

# For the area calculation

area = pweibull(6, shape= 1, scale=9)-pweibull(2, shape = 1, scale = 9)
area=round(area,4)

text(x= 5, y= 0.15, paste("Area= ", area, sep= ""))


# Y~dweibull(shape= 10 , scale= 15   ), P(2Y≤7)

curve(dweibull(x,shape= 10 ,scale=15 ),xlim=c(0,20),ylim=c(0,0.3),col="Red",lwd=2,

ylab="Weibull density", xlab= "X", main="Shape 10 Scale 15")

xcurve= seq(10,15, length= 1000)

ycurve= dweibull(xcurve, shape=10, scale=15)

polygon(c(10, xcurve, 15), c(0, ycurve, 0), col= "Yellow")

# For the area calculation

area = pweibull(7, shape= 10, scale=15)-pweibull(2, shape = 10, scale = 15)
area=round(area,4)

text(x= 5, y= 0.15, paste("Area= ", area, sep= ""))



 




```
# Task 6 

```{r}
layout(matrix(1:4, nr=2, nc=2 ))
layout.show(4)

# These plots plot the density of 

# P((3≤Y≤6))

curve(dbeta(x,shape1 =2,shape2=3), xlim=c(0,1) ,

ylab="Beta density", xlab = "X", main="Shape1 =2, shape2= 3")

xcurve= seq(.2,.8, length= 1000)

ycurve= dbeta(xcurve, shape1= 2 , shape2= 3)  

polygon(c(.2, xcurve, .8), c(0, ycurve, 0), col= "Yellow")

# For the area calculation

area = pbeta(.8, shape1= 2, shape2= 3)-pbeta(.2, shape1=2, shape2= 3)
area=round(area,4)

text(x= 0.5, y= 1.0, paste("Area= ", area, sep= ""))




curve(dbeta(x,shape1 =4,shape2=7), xlim=c(0,1) ,

ylab="Beta density", xlab = "X", main="Shape1 =4, shape2= 7")

xcurve= seq(.2,.8, length= 1000)

ycurve= dbeta(xcurve, shape1= 4 , shape2= 7)  

polygon(c(.2, xcurve, .8), c(0, ycurve, 0), col= "Yellow")

# For the area calculation

area = pbeta(.8, shape1= 4, shape2= 7)-pbeta(.2, shape1=4, shape2= 7)
area=round(area,4)

text(x= 0.5, y= 1.0, paste("Area= ", area, sep= ""))


curve(dbeta(x,shape1 =5,shape2=9), xlim=c(0,1) ,

ylab="Beta density", xlab = "X", main="Shape1 =5, shape2= 9")

xcurve= seq(.2,.8, length= 1000)

ycurve= dbeta(xcurve, shape1= 5 , shape2= 9)  

polygon(c(.2, xcurve, .8), c(0, ycurve, 0), col= "Yellow")

# For the area calculation

area = pbeta(.8, shape1= 5, shape2= 9)-pbeta(.2, shape1=5, shape2= 9)
area=round(area,4)

text(x= 0.5, y= 1.0, paste("Area= ", area, sep= ""))


curve(dbeta(x,shape1 =12,shape2=18), xlim=c(0,1) ,

ylab="Beta density", xlab = "X", main="Shape1 =12, shape2= 18")

xcurve= seq(.2,.8, length= 1000)

ycurve= dbeta(xcurve, shape1= 12 , shape2= 18)  

polygon(c(.2, xcurve, .8), c(0, ycurve, 0), col= "Yellow")

# For the area calculation

area = pbeta(.8, shape1= 12, shape2= 18)-pbeta(.2, shape1= 12, shape2= 18)
area=round(area,4)

text(x= 0.5, y= 1.0, paste("Area= ", area, sep= ""))



```

# Task 7

```{r}
library(RIGHTMATH4752)
RIGHTMATH4752::myncurve(10,5,6)
```






